name: Moon Backend Pull Request

on:
  push:
    branches-ignore:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ github.ref_name }}
          base: main
          title: "Pull request from ${{ github.ref_name }}"
          body: "Automated PR created from branch ${{ github.ref_name }}"
