name: Moon Backend Pull Request

on:
  push:
    branches-ignore:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Pull Request
        run: gh pr create --base main --head ${{ github.ref_name }} --title "${{ github.ref_name }}" --body "Automated PR created from branch ${{ github.ref_name }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
